<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Moq"  />
        <PackageReference Include="Grpc.Core.Testing"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Contracts\Axorith.Contracts.csproj" />
        <ProjectReference Include="..\..\src\Host\Axorith.Host.csproj" />
        <ProjectReference Include="..\..\src\Core\Axorith.Core.csproj" />
    </ItemGroup>
</Project>
