<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Shim</AssemblyName>
        <RootNamespace>Axorith.Shim</RootNamespace>

        <Description>Shim for Axorith.</Description>
        
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\Utils\Axorith.Shared.Utils.csproj" />
    </ItemGroup>
</Project>