<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Module.OBS</AssemblyName>
        <RootNamespace>Axorith.Module.OBS</RootNamespace>

        <Description>OBS Studio module for Axorith</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Sdk\Axorith.Sdk.csproj" />
        <ProjectReference Include="..\..\Shared\Utils\Axorith.Shared.Utils.csproj" />
        <ProjectReference Include="..\..\Shared\Exceptions\Axorith.Shared.Exceptions.csproj" />
        <ProjectReference Include="..\..\Shared\Platform\Axorith.Shared.Platform.csproj" />
        <ProjectReference Include="..\..\Shared\ApplicationLauncher\Axorith.Shared.ApplicationLauncher.csproj" />
    </ItemGroup>
</Project>
