<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Moq"  />
        <PackageReference Include="Avalonia.Headless.XUnit"  />
        <PackageReference Include="Grpc.Net.Client"  />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Contracts\Axorith.Contracts.csproj" />
        <ProjectReference Include="..\..\src\Host\Axorith.Host.csproj" />
        <ProjectReference Include="..\..\src\Core\Axorith.Core.csproj" />
        <ProjectReference Include="..\..\src\Client\Axorith.Client.csproj" />
        <ProjectReference Include="..\..\src\Modules\ApplicationLauncher\Axorith.Module.ApplicationLauncher.csproj" />
        <ProjectReference Include="..\..\src\Modules\AppBlocker\Axorith.Module.AppBlocker.csproj" />
        <ProjectReference Include="..\..\src\Modules\SiteBlocker\Axorith.Module.SiteBlocker.csproj" />
        <ProjectReference Include="..\..\src\Modules\HomeAssistant\Axorith.Module.HomeAssistant.csproj" />
    </ItemGroup>
</Project>
