<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Sdk</AssemblyName>
        <RootNamespace>Axorith.Sdk</RootNamespace>
        
        <Description>Software Development Kit (SDK) for creating Axorith modules.</Description>
        
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        
        <!-- SDK optimizations -->
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="System.Reactive" Version="6.1.0" />
    </ItemGroup>
</Project>