<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Moq"  />
        <PackageReference Include="Microsoft.Reactive.Testing"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Core\Axorith.Core.csproj" />
        <ProjectReference Include="..\..\src\Shared\Exceptions\Axorith.Shared.Exceptions.csproj" />
        <ProjectReference Include="..\..\src\Modules\SiteBlocker\Axorith.Module.SiteBlocker.csproj" />
    </ItemGroup>
</Project>
