<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Shared.Platform</AssemblyName>
        <RootNamespace>Axorith.Shared.Platform</RootNamespace>

        <Description>Platform-specific implementations for Axorith (Windows, Linux, macOS)</Description>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Axorith.Shared.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Sdk\Axorith.Sdk.csproj" />
        <ProjectReference Include="..\..\Telemetry\Axorith.Telemetry.csproj" />
        <ProjectReference Include="..\Utils\Axorith.Shared.Utils.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ace4896.DBus.Services.Secrets" Version="1.4.0" />
        <PackageReference Include="System.Management" Version="10.0.0" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.28" />

    </ItemGroup>
</Project>