<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Moq"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shared\Utils\Axorith.Shared.Utils.csproj" />
        <ProjectReference Include="..\..\src\Shared\Platform\Axorith.Shared.Platform.csproj" />
    </ItemGroup>

</Project>
