<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Core</AssemblyName>
        <RootNamespace>Axorith.Core</RootNamespace>
        
        <Description>Core system for Axorith.</Description>
        
        <!-- Library optimizations -->
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Axorith.Core.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Sdk\Axorith.Sdk.csproj" />
        <ProjectReference Include="..\Shared\Platform\Axorith.Shared.Platform.csproj" />
        <ProjectReference Include="..\Shared\Utils\Axorith.Shared.Utils.csproj" />
        <ProjectReference Include="..\Shared\Exceptions\Axorith.Shared.Exceptions.csproj" />
        <ProjectReference Include="..\Telemetry\Axorith.Telemetry.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac"  />
      <PackageReference Include="Microsoft.Extensions.Logging"  />
      <PackageReference Include="Serilog"  />
    </ItemGroup>
</Project>
