<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Axorith.Module.Steam</AssemblyName>
        <RootNamespace>Axorith.Module.Steam</RootNamespace>
        <Description>Steam module for Axorith - launch Steam and games.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Sdk\Axorith.Sdk.csproj" />
        <ProjectReference Include="..\..\Shared\Platform\Axorith.Shared.Platform.csproj" />
        <ProjectReference Include="..\..\Shared\ApplicationLauncher\Axorith.Shared.ApplicationLauncher.csproj" />
    </ItemGroup>
</Project>
